wallets:
  - label: Unipcs
    source: FOMO
    address: "0x0a6ebed0155edb4b21d92ad02897a626cd90119e"
    chains: [robinhood]
    weight: 1.0

  - label: test
    source: GMGN
    address: "0x5f72eac252211a8ccfde64cc15e2155468139220"
    chains: [bsc]
    weight: 1.0

  - label: test02
    source: GMGN
    address: "0x4636565ac6352902403d1146c45492b8a5ebad55"
    chains: [robinhood]
    weight: 1.0

  - label: test03
    source: GMGN
    address: "0xb01c92e0cfe2858bfb609abef7e6168c92b2ea0e"
    chains: [robinhood]
    weight: 1.0

  - label: test04
    source: GMGN
    address: "0x55f3422138e9fed0bd81351bff66c882550002e8"
    chains: [robinhood]
    weight: 1.0

  - label: test05
    source: GMGN
    address: "0xd4d8a5f5ad99349ae53746926b077505ead139aa"
    chains: [robinhood]
    weight: 1.0
